version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./dumps:/var/dumps
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./source/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - ./source/themes/quis:/var/www/html/wp-content/themes/quis
       - ./source/plugins/wp-no-category-base:/var/www/html/wp-content/plugins/wp-no-category-base
       - ./source/plugins/pc-admin-page-ids:/var/www/html/wp-content/plugins/pc-admin-page-ids
       - ./source/plugins/google-sitemap-generator:/var/www/html/wp-content/plugins/google-sitemap-generator
       - ./source/plugins/qInlineImages.php:/var/www/html/wp-content/plugins/qInlineImages.php
volumes:
    db_data:
